#if !defined SHFOPUSFILE_INCLUDED
#define SHFOPUSFILE_INCLUDED

#if defined SHFOPUSFILE_IMPLEMENTATION

#include "sort.c"
#include "lin2log.c"
#include "log2lin.c"
#include "NLSF_stabilize.c"
#include "LPC_fit.c"
#include "bwexpander_32.c"
#include "gain_quant.c"
#include "NLSF_decode.c"
#include "pitch_est_tables.c"
#include "decode_pitch.c"
#include "table_LSF_cos.c"
#include "NLSF2A.c"
#undef QA
#include "bwexpander.c"
#include "LPC_inv_pred_gain.c"
#include "LPC_analysis_filter.c"
#include "sum_sqr_shift.c"
#include "resampler_private_AR2.c"
#include "NLSF_unpack.c"
#include "decode_parameters.c"
#include "decode_core.c"
#include "CNG.c"
#include "PLC.c"
#include "resampler_private_up2_HQ.c"
#include "resampler_private_IIR_FIR.c"
#include "resampler_private_down_FIR.c"
#include "kiss_fft.c"
#include "shell_coder.c"
#include "code_signs.c"
#include "init_decoder.c"
#include "tables_NLSF_CB_WB.c"
#include "tables_NLSF_CB_NB_MB.c"
#include "decoder_set_fs.c"
#include "tables_LTP.c"
#include "tables_pitch_lag.c"
#include "tables_gain.c"
#include "decode_indices.c"
#include "stereo_decode_pred.c"
#include "decode_frame.c"
#include "stereo_MS_to_LR.c"
#include "resampler_rom.c"
#include "resampler.c"
#include "mdct.c"
#include "cwrs.c"
#include "tables_pulses_per_block.c"
#include "decode_pulses.c"
#include "laplace.c"
#include "mathops.c"
#include "entenc.c"
#include "entcode.c"
#include "entdec.c"
#include "tables_other.c"
#include "dec_API.c"

#include "celt_decoder.c"
#include "modes.c"
#include "pitch.c"
#include "celt_lpc.c"
#include "rate.c"
#include "vq.c"
#include "quant_bands.c"
#include "bands.c"
#include "celt.c"

#include "internal.c"
#include "opus_multistream.c"
#include "opus_decoder.c"
#include "info.c"
#include "stream.c"
#include "framing.c"
#include "opus_multistream_decoder.c"
#include "opus.c"
#include "opusfile.c"

#endif

#endif
